name: build

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Tests
        run: |
          go mod tidy
          go test -v ./...
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  build-client:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Tests
        run: |
          go mod tidy
          go test -v ./...
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run GoReleaser - Client
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: ./client
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Run GoReleaser - Docs
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: ./docs
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Run GoReleaser - Driver
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: ./driver
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Run GoReleaser - Go
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: ./go
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}